// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxO9l-_PQxYCqfOGu8xuUL5xTijeomyAM',
    appId: '1:252094082264:web:d0b00832ddc8d17b2dbbad',
    messagingSenderId: '252094082264',
    projectId: 'atlasai-hackathon-sd-2026',
    authDomain: 'atlasai-hackathon-sd-2026.firebaseapp.com',
    storageBucket: 'atlasai-hackathon-sd-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkWED1Zt1EA5roOsPgdyeITqR1kl1WI30',
    appId: '1:252094082264:android:543be36ba29e026c2dbbad',
    messagingSenderId: '252094082264',
    projectId: 'atlasai-hackathon-sd-2026',
    storageBucket: 'atlasai-hackathon-sd-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2eWiID2rVWPqhJAa3z4oh1TK8x6FhpI',
    appId: '1:252094082264:ios:fba0941bb949dd5f2dbbad',
    messagingSenderId: '252094082264',
    projectId: 'atlasai-hackathon-sd-2026',
    storageBucket: 'atlasai-hackathon-sd-2026.firebasestorage.app',
    iosBundleId: 'com.example.atlasaiApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN2eWiID2rVWPqhJAa3z4oh1TK8x6FhpI',
    appId: '1:252094082264:ios:fba0941bb949dd5f2dbbad',
    messagingSenderId: '252094082264',
    projectId: 'atlasai-hackathon-sd-2026',
    storageBucket: 'atlasai-hackathon-sd-2026.firebasestorage.app',
    iosBundleId: 'com.example.atlasaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxO9l-_PQxYCqfOGu8xuUL5xTijeomyAM',
    appId: '1:252094082264:web:dd659e7ccbcfa1b12dbbad',
    messagingSenderId: '252094082264',
    projectId: 'atlasai-hackathon-sd-2026',
    authDomain: 'atlasai-hackathon-sd-2026.firebaseapp.com',
    storageBucket: 'atlasai-hackathon-sd-2026.firebasestorage.app',
  );
}
